language: java
java:
  - "1.8.0"
sudo: true
branches:
  only:
    - master

before_install:
  - chmod +x mvnw


cache:
  yarn: true


after_deploy:
  - mvn clean package
  - mv ./target/portfolio-back-end-0.0.1-SNAPSHOT.jar ./application.jar

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  region: "us-east-2"
  app: "PortfolioSite"
  env : "Portfoliosite-env"
  bucket_name: "elasticbeanstalk-us-east-2-841421274623"
