language: java
java:
  - "1.8.0"
sudo: true

env:
  global:
    - SPRING_PROFILES_ACTIVE = production
branches:
  only:
    - master

before_install:
  - chmod +x mvnw

cache:
  yarn: true


script:
  - mvn clean  package
  - mv ./target/portfolio-back-end-0.0.1-SNAPSHOT.jar ./application.jar

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  region: "us-east-2"
  app: "AccessedPortfolio"
  env : "Accessedportfolio-env"
  bucket_name: "elasticbeanstalk-us-east-2-841421274623"
  zip_file: "./application.jar"
  #  The clean up is skipped so that the jar file would not be removed
  skip_cleanup: true