language: java
java:
  - "1.8.0"
sudo: true
branches:
  only:
    - master

before_install:
  - chmod +x mvnw


cache:
  yarn: true


script:
  - mvn clean  package

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  region: "us-east-2"
  app: "AccessedPortfolio"
  env : "Accessedportfolio-env"
  bucket_name: "elasticbeanstalk-us-east-2-841421274623"
  zip_file: "./target/portfolio-back-end-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true